### ISSUE TITLE
'<=' not supported between instances of 'tuple' and 'int'

### ISSUE THREAD

**Issue by pouemes** [nederhof/hocr#1]
File "D:\hocr\src\imageprocessing.py", line 49, in is_black
    return in_image(im, x, y) and im.getpixel((x,y)) <= threshold
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'tuple' and 'int'

**Comment by nederhof** [comment]
Input images should be grayscale.
